#!/usr/bin/env bash
# setup.sh — Developer onboarding script for the Claude Cadence full-stack local environment.
#
# Wraps docker-compose.dev.yml to start all services (issues API, issues UI,
# Caddy, agent-hub, agentd) with secure auto-generated tokens.
#
# Usage:
#   bash scripts/setup.sh [--port PORT]
#
# For advanced configuration (TLS, low ports, production), see docs/dev-environment.md.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ---- Color helpers -----------------------------------------------------------

info()  { printf '\033[0;34m==> %s\033[0m\n' "$*"; }
warn()  { printf '\033[0;33mWARN: %s\033[0m\n' "$*" >&2; }
error() { printf '\033[0;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# ---- Usage -------------------------------------------------------------------

usage() {
    cat <<EOF
Usage: bash scripts/setup.sh [--port PORT]

Starts the full Claude Cadence dev stack and opens the UI in your browser.

Services started:
  - issues-api   (issues microservice backend)
  - issues-ui    (issues microservice frontend)
  - agent-hub    (WebSocket coordination hub)
  - agentd       (agent daemon)
  - caddy        (reverse proxy, serves UI on PORT)

Options:
  --port PORT    Host port to bind the UI on (default: 8080)
  -h, --help     Show this help message

Requirements:
  - Docker with the Compose plugin (docker compose)
  - ~/.claude directory (agentd mounts this for Claude credentials)

Advanced setups (TLS, low ports, production) require manual configuration.
See docs/dev-environment.md for details.
EOF
}

# ---- Prerequisite checks -----------------------------------------------------

check_prereqs() {
    local missing=()

    if ! command -v docker > /dev/null 2>&1; then
        missing+=("docker")
    fi

    if ! docker compose version > /dev/null 2>&1; then
        missing+=("docker compose (Compose plugin)")
    fi

    if [ "${#missing[@]}" -gt 0 ]; then
        error "Missing required tools: ${missing[*]}. Install them and retry."
    fi

    info "Prerequisites satisfied."
}

# ---- ~/.claude check ---------------------------------------------------------

check_claude_dir() {
    if [ ! -d "$HOME/.claude" ]; then
        warn "\$HOME/.claude does not exist. agentd requires it to access Claude credentials."
        warn "Create it (mkdir -p \$HOME/.claude) or agent sessions may fail to start."
    fi
}

# ---- .env.dev setup ----------------------------------------------------------

setup_env() {
    local env_file="$REPO_ROOT/.env.dev"

    if [ -f "$env_file" ]; then
        warn ".env.dev already exists — skipping auto-generation. Delete it to regenerate."
        return
    fi

    info "Generating .env.dev with secure random tokens..."

    local hub_api_token hub_agent_token agentd_token
    hub_api_token="$(openssl rand -hex 32)"
    hub_agent_token="$(openssl rand -hex 32)"
    agentd_token="$(openssl rand -hex 32)"

    # Write with restricted permissions (owner read/write only)
    (umask 077 && cat > "$env_file" <<EOF
# Auto-generated by scripts/setup.sh
# For advanced configuration options, see docs/dev-environment.md
HUB_API_TOKEN=${hub_api_token}
HUB_AGENT_TOKEN=${hub_agent_token}
AGENTD_TOKEN=${agentd_token}
EOF
)

    info ".env.dev created."
}

# ---- Start stack -------------------------------------------------------------

start_stack() {
    local port="$1"
    local project_name="cadence-dev-${port}"

    info "Starting stack (project: ${project_name}, port: ${port})..."

    QA_PORT="$port" \
    docker compose \
        -f "$REPO_ROOT/docker-compose.dev.yml" \
        -p "$project_name" \
        up --build -d

    local url="http://localhost:${port}/"

    printf '\n'
    info "Stack is up: ${url}"
    printf '\n'
    printf 'Management commands:\n'
    printf '  Restart agentd:  docker compose -p %s restart agentd\n' "$project_name"
    printf '  View logs:       docker compose -p %s logs -f\n' "$project_name"
    printf '  Stop:            docker compose -p %s down\n' "$project_name"
    printf '\n'

    # Open browser best-effort
    if command -v xdg-open > /dev/null 2>&1; then
        xdg-open "$url" > /dev/null 2>&1 &
    elif command -v open > /dev/null 2>&1; then
        open "$url" &
    fi
}

# ---- Main --------------------------------------------------------------------

main() {
    local port=8080

    while [ "$#" -gt 0 ]; do
        case "$1" in
            --port)
                [ "$#" -ge 2 ] || error "--port requires an argument"
                port="$2"
                case "$port" in
                    ''|*[!0-9]*) error "--port must be a number (e.g. 8080)" ;;
                esac
                [ "$port" -ge 1024 ] && [ "$port" -le 65535 ] || error "--port must be between 1024 and 65535"
                shift 2
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                error "Unknown option: $1. Run with -h for usage."
                ;;
        esac
    done

    check_prereqs
    check_claude_dir
    setup_env
    start_stack "$port"
}

main "$@"
