#!/usr/bin/env python3
"""Generate thin Codex skill wrappers from the Claude Cadence source files."""

from __future__ import annotations

from pathlib import Path
import re
import shutil


ROOT = Path(__file__).resolve().parent.parent
DEST_ROOT = ROOT / "codex" / "skills"

SOURCE_GROUPS = [
    ("command", ROOT / "commands", "SKILL.md"),
    ("skill", ROOT / "skills", "SKILL.md"),
    ("agent", ROOT / "agents", "*.md"),
]


def parse_frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text()
    match = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    fields: dict[str, str] = {}
    if not match:
        return fields

    for line in match.group(1).splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        fields[key.strip()] = value.strip().strip("\"'")
    return fields


def source_relpath(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def wrapper_body(kind: str, source_path: Path, name: str, description: str) -> str:
    rel = source_relpath(source_path)
    display_name = name.replace("-", " ").title()
    if kind == "command":
        role_line = (
            "This is a Codex entrypoint wrapper for a Claude Cadence user-facing workflow."
        )
        translation = [
            "Treat Claude slash-command references as this Codex skill.",
            "When the source workflow says to delegate with an agent, use Codex sub-agents when available or perform the work locally when that keeps the critical path moving.",
        ]
    elif kind == "agent":
        role_line = (
            "This is a Codex specialist-role wrapper for a Claude Cadence agent definition."
        )
        translation = [
            "Adopt the specialist persona, scope, and review criteria from the source file.",
            "Use Codex tools and delegation patterns instead of Claude-specific tool names, but preserve the intent and guardrails.",
        ]
    else:
        role_line = "This is a Codex wrapper for a Claude Cadence shared skill."
        translation = [
            "Reuse the existing scripts and command examples from the source file.",
            "Translate only the runtime mechanics needed to execute the workflow in Codex.",
        ]

    lines = [
        "---",
        f"name: {name}",
        f"description: {description}",
        "---",
        "",
        f"# {display_name}",
        "",
        role_line,
        "",
        "Source of truth:",
        f"- `../../../{rel}`",
        "- `../../../CLAUDE.md`",
        "",
        "Instructions:",
        f"1. Read `../../../{rel}` before taking action.",
        "2. Read `../../../CLAUDE.md` for repo-wide Cadence rules, ticket provider configuration, and verification commands.",
    ]
    for idx, item in enumerate(translation, start=3):
        lines.append(f"{idx}. {item}")
    lines.extend(
        [
            f"{len(translation) + 3}. Do not duplicate or fork the workflow here unless Codex-specific packaging requires it.",
            f"{len(translation) + 4}. When this wrapper and the source file disagree, follow `../../../{rel}` and update the wrapper generation rather than patching the generated file manually.",
            "",
            f"Canonical description: {description}",
            "",
            "<!-- Generated by scripts/sync-codex.py. Edit the Claude source file or the generator, then re-run the script. -->",
            "",
        ]
    )
    return "\n".join(lines)


def iter_sources() -> list[tuple[str, Path, str, str]]:
    items: list[tuple[str, Path, str, str]] = []
    for kind, base_dir, pattern in SOURCE_GROUPS:
        if kind == "agent":
            for source_path in sorted(base_dir.glob(pattern)):
                fields = parse_frontmatter(source_path)
                name = fields.get("name", source_path.stem)
                description = fields.get("description", f"Codex wrapper for {name}")
                items.append((kind, source_path, name, description))
            continue

        for source_path in sorted(base_dir.glob(f"*/{pattern}")):
            fields = parse_frontmatter(source_path)
            name = fields.get("name", source_path.parent.name)
            description = fields.get("description", f"Codex wrapper for {name}")
            items.append((kind, source_path, name, description))
    return items


def main() -> None:
    if DEST_ROOT.exists():
        shutil.rmtree(DEST_ROOT)
    DEST_ROOT.mkdir(parents=True, exist_ok=True)

    for kind, source_path, name, description in iter_sources():
        skill_dir = DEST_ROOT / name
        skill_dir.mkdir(parents=True, exist_ok=True)
        output = wrapper_body(kind, source_path, name, description)
        (skill_dir / "SKILL.md").write_text(output)

    print(f"Generated {len(list(DEST_ROOT.glob('*/SKILL.md')))} Codex skills in {DEST_ROOT}")


if __name__ == "__main__":
    main()
