#!/usr/bin/env bash
set -euo pipefail

# agentd interactive installer
# Installs the agent service as a system daemon using launchd (macOS) or systemd (Linux).

LABEL="com.cadence.agentd"
BINARY_NAME="agentd"
DEFAULT_HOST="127.0.0.1"
DEFAULT_PORT="4141"
DEFAULT_ROOT_DIR="/var/lib/agentd"
DEFAULT_CONFIG_DIR=""
DEFAULT_LOG_DIR=""
INSTALL_DIR="/usr/local/bin"

# --- Helpers ---

info()  { printf "\033[1;34m==>\033[0m %s\n" "$1"; }
warn()  { printf "\033[1;33mWarning:\033[0m %s\n" "$1"; }
error() { printf "\033[1;31mError:\033[0m %s\n" "$1" >&2; exit 1; }

prompt() {
    local var_name="$1" prompt_text="$2" default="$3"
    local value
    printf "%s [%s]: " "$prompt_text" "$default"
    read -r value
    eval "$var_name=\"${value:-$default}\""
}

confirm() {
    local response
    printf "%s [y/N]: " "$1"
    read -r response
    [[ "$response" =~ ^[Yy]$ ]]
}

# --- Platform detection ---

detect_os() {
    case "$(uname -s)" in
        Darwin) echo "darwin" ;;
        Linux)  echo "linux" ;;
        *)      error "Unsupported operating system: $(uname -s)" ;;
    esac
}

# --- Prerequisite checks ---

check_prerequisites() {
    info "Checking prerequisites..."
    local missing=()

    command -v git >/dev/null 2>&1 || missing+=("git")
    command -v tmux >/dev/null 2>&1 || missing+=("tmux")

    if [[ ${#missing[@]} -gt 0 ]]; then
        error "Required tools not found: ${missing[*]}. Please install them and re-run."
    fi

    command -v vault >/dev/null 2>&1 || warn "vault CLI not found (optional, needed for private repos)"
    command -v ttyd >/dev/null 2>&1  || warn "ttyd not found (optional, needed for web terminal access)"

    info "Prerequisites satisfied."
}

# --- User management ---

setup_user() {
    local os="$1"
    prompt AGENTD_USER "User to run the service as" "$(whoami)"

    if ! id "$AGENTD_USER" >/dev/null 2>&1; then
        info "User '$AGENTD_USER' does not exist."
        if confirm "Create system user '$AGENTD_USER'?"; then
            if [[ "$os" == "darwin" ]]; then
                # macOS: use sysadminctl or dscl
                sudo dscl . -create "/Users/$AGENTD_USER"
                sudo dscl . -create "/Users/$AGENTD_USER" UserShell /usr/bin/false
                sudo dscl . -create "/Users/$AGENTD_USER" RealName "agentd service"
                info "Created user '$AGENTD_USER' on macOS."
            else
                sudo useradd --system --shell /usr/bin/false --create-home "$AGENTD_USER"
                info "Created system user '$AGENTD_USER'."
            fi
        else
            error "User '$AGENTD_USER' does not exist. Aborting."
        fi
    fi

    AGENTD_GROUP="$(id -gn "$AGENTD_USER")"
}

# --- Directory setup ---

setup_directories() {
    local os="$1"

    if [[ "$os" == "darwin" ]]; then
        DEFAULT_CONFIG_DIR="$HOME/.config/agentd"
        DEFAULT_LOG_DIR="$HOME/Library/Logs/agentd"
    else
        DEFAULT_CONFIG_DIR="/etc/agentd"
        DEFAULT_LOG_DIR="/var/log/agentd"
    fi

    prompt AGENTD_ROOT_DIR "Root directory for repos and worktrees" "$DEFAULT_ROOT_DIR"
    prompt AGENTD_CONFIG_DIR "Config directory" "$DEFAULT_CONFIG_DIR"
    prompt AGENTD_LOG_DIR "Log directory" "$DEFAULT_LOG_DIR"

    info "Creating directories..."
    sudo mkdir -p "$AGENTD_ROOT_DIR/repos" "$AGENTD_ROOT_DIR/worktrees"
    sudo chown -R "$AGENTD_USER:$AGENTD_GROUP" "$AGENTD_ROOT_DIR"

    mkdir -p "$AGENTD_CONFIG_DIR"
    mkdir -p "$AGENTD_LOG_DIR"
}

# --- Config generation ---

generate_config() {
    local config_path="$AGENTD_CONFIG_DIR/config.yaml"

    if [[ -f "$config_path" ]]; then
        warn "Config already exists at $config_path"
        if ! confirm "Overwrite?"; then
            info "Keeping existing config."
            return
        fi
    fi

    info "Generating config at $config_path..."
    cat > "$config_path" <<EOF
# agentd configuration — generated by install.sh

host: "$AGENTD_HOST"
port: $AGENTD_PORT

root_dir: "$AGENTD_ROOT_DIR"

tmux:
  socket_name: "agentd"

ttyd:
  enabled: false
  base_port: 7681

log:
  level: "info"
  format: "json"

# Add agent profiles below:
profiles: {}
EOF

    info "Config written to $config_path"
}

# --- Binary installation ---

install_binary() {
    local script_dir
    script_dir="$(cd "$(dirname "$0")" && pwd)"
    local service_dir="$script_dir/.."

    if [[ -f "$service_dir/agentd" ]]; then
        info "Installing pre-built binary to $INSTALL_DIR/$BINARY_NAME..."
        sudo cp "$service_dir/agentd" "$INSTALL_DIR/$BINARY_NAME"
    elif command -v go >/dev/null 2>&1 && [[ -f "$service_dir/go.mod" ]]; then
        info "Building agentd from source..."
        (cd "$service_dir" && go build -o agentd ./cmd/agentd)
        sudo cp "$service_dir/agentd" "$INSTALL_DIR/$BINARY_NAME"
    else
        error "No agentd binary found and Go is not installed. Build first with 'make build'."
    fi

    sudo chmod 755 "$INSTALL_DIR/$BINARY_NAME"
    info "Binary installed to $INSTALL_DIR/$BINARY_NAME"
}

# --- Template rendering ---

render_template() {
    local template="$1" output="$2"
    sed \
        -e "s|__BINARY_PATH__|$INSTALL_DIR/$BINARY_NAME|g" \
        -e "s|__CONFIG_PATH__|$AGENTD_CONFIG_DIR/config.yaml|g" \
        -e "s|__USER__|$AGENTD_USER|g" \
        -e "s|__GROUP__|$AGENTD_GROUP|g" \
        -e "s|__ROOT_DIR__|$AGENTD_ROOT_DIR|g" \
        -e "s|__LOG_DIR__|$AGENTD_LOG_DIR|g" \
        "$template" > "$output"
}

# --- Service installation ---

install_launchd() {
    local script_dir
    script_dir="$(cd "$(dirname "$0")" && pwd)"
    local plist_tmpl="$script_dir/agentd.plist.tmpl"
    local plist_dest="$HOME/Library/LaunchAgents/$LABEL.plist"

    if [[ ! -f "$plist_tmpl" ]]; then
        error "launchd template not found: $plist_tmpl"
    fi

    info "Installing launchd service..."
    mkdir -p "$HOME/Library/LaunchAgents"
    render_template "$plist_tmpl" "$plist_dest"

    # Unload if already loaded, ignore errors.
    launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true

    launchctl bootstrap "gui/$(id -u)" "$plist_dest"
    info "launchd service installed and started."
}

install_systemd() {
    local script_dir
    script_dir="$(cd "$(dirname "$0")" && pwd)"
    local unit_tmpl="$script_dir/agentd.service.tmpl"
    local unit_dest="/etc/systemd/system/agentd.service"

    if [[ ! -f "$unit_tmpl" ]]; then
        error "systemd template not found: $unit_tmpl"
    fi

    info "Installing systemd service..."
    local rendered
    rendered="$(mktemp)"
    render_template "$unit_tmpl" "$rendered"
    sudo cp "$rendered" "$unit_dest"
    rm -f "$rendered"

    sudo systemctl daemon-reload
    sudo systemctl enable agentd
    sudo systemctl start agentd
    info "systemd service installed, enabled, and started."
}

# --- Health check ---

health_check() {
    info "Waiting for service to start..."
    local retries=10
    while [[ $retries -gt 0 ]]; do
        if command -v grpcurl >/dev/null 2>&1; then
            if grpcurl -plaintext "$AGENTD_HOST:$AGENTD_PORT" list >/dev/null 2>&1; then
                info "Service is healthy!"
                return 0
            fi
        else
            # Fall back to checking if the port is open.
            if (echo >/dev/tcp/"$AGENTD_HOST"/"$AGENTD_PORT") 2>/dev/null; then
                info "Service is listening on $AGENTD_HOST:$AGENTD_PORT"
                return 0
            fi
        fi
        retries=$((retries - 1))
        sleep 1
    done

    warn "Could not verify service health. Check logs at $AGENTD_LOG_DIR/"
    return 1
}

# --- Main ---

main() {
    info "agentd installer"
    echo

    local os
    os="$(detect_os)"
    info "Detected platform: $os"

    check_prerequisites
    setup_user "$os"

    prompt AGENTD_HOST "Host to bind to" "$DEFAULT_HOST"
    prompt AGENTD_PORT "Port to listen on" "$DEFAULT_PORT"

    setup_directories "$os"
    install_binary
    generate_config

    case "$os" in
        darwin) install_launchd ;;
        linux)  install_systemd ;;
    esac

    health_check

    echo
    info "Installation complete!"
    info "Config: $AGENTD_CONFIG_DIR/config.yaml"
    info "Binary: $INSTALL_DIR/$BINARY_NAME"
    info "Root:   $AGENTD_ROOT_DIR"
    echo
    info "Next steps:"
    info "  1. Edit $AGENTD_CONFIG_DIR/config.yaml to add agent profiles"
    info "  2. Restart the service after config changes:"
    if [[ "$os" == "darwin" ]]; then
        info "     launchctl kickstart -k gui/$(id -u)/$LABEL"
    else
        info "     sudo systemctl restart agentd"
    fi
}

main "$@"
